site_name: Studium
site_description: Biblioteca académica abierta y estructurada
site_url: https://alainmuniz.github.io/studium/
site_author: Studium

theme:
  name: material

plugins:
  - search

nav:
  - Inicio: index.md

  - Demo University:
      - Inicio: demo-university/index.md

      - Cursos:
          - Grado en Derecho: demo-university/courses/grado-derecho.md

      - Asignaturas:
          - Derecho Internacional Público:
              - Información: demo-university/subjects/20405-derecho-internacional-publico/index.md
              - Tema 1: demo-university/subjects/20405-derecho-internacional-publico/tema-1.md
